version: "3.9"

services:

  server:
    build: .
    ports:
      - "8080:8080"
    networks:
      - webnet
    command: ["python3", "server.py"]
  
  prometheus:
    image: prom/prometheus:v2.40.7
    volumes: 
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - webnet

  grafana:
    image: grafana/grafana:9.4.2
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/default.yaml
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./grafana/config.ini:/etc/grafana/grafana.ini
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

  
    


    

  